name: Build CLI app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true

      - name: Install PCSC for Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get install libpcsclite-dev gengetopt -y

      - name: Build
        run: cargo build --release

      - name: Prepare releases directory
        run: mkdir -p releases || md releases

      - name: Copy Windows binary for release
        if: runner.os == 'Windows'
        run: |
          copy target/release/yubikey_encrypt.exe releases/yubikey_encrypt.exe

      - name: Copy binary for release
        if: runner.os == 'Linux' || runner.os == 'Windows'
        run: |
          cp target/release/yubikey_encrypt releases/yubikey_encrypt

      - name: Generate SHA256 checksums for macOS
        if: runner.os == 'macOS'
        run: |
          cd releases/
          shasum -a 256 * > SHA256CHECKSUMS.txt

      - name: Generate checksums for Linux and Windows
        if: runner.os == 'Linux' || runner.os == 'Windows'
        run: |
          cd releases/
          sha256sum * > SHA256CHECKSUMS.txt

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.7.0
        with:
          file: releases/*
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
